[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'Custom branding'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-cli-arsclib"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
excluded-patches = "'Custom branding'"
