[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
#rv-brand = "inotia00 ReVanced"
excluded-patches = "'Custom branding'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-cli-arsclib"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "Reddit"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
#rv-brand = "inotia00 ReVanced"
excluded-patches = "'Custom branding'"

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

#[Soundcloud]
#uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud"
#arch = "arm64-v8a"

#[Lightroom]
#uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom"
#arch = "arm64-v8a"

[Spotify]
# apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
version = "9.0.36.683"
arch = "arm64-v8a"
